nodeLinker: node-modules

packageExtensions:
  "@testing-library/react@^12.1.2":
    dependencies:
      react-dom: next
  "@vanilla-extract/webpack-plugin@^2.1.0":
    dependencies:
      "@vanilla-extract/css": ^1.6.0
  babel-preset-react-app@10.0.1:
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": ^7.16.7
  react-dev-utils@^10.2.1:
    dependencies:
      typescript: ^4.3.5
      webpack: ^5.9.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
